# Deploy Springboot app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
    ref: commit
  name: spring
spec:
  clusterIP: None
  ports:
    - name: spring
      port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: springboot
    ref: commit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
        ref: commit
    spec:
      containers:
        - name: spring
          image: registry.gitlab.com/florian935/spring-customci-k8s:latest
          ports:
            - containerPort: 8080
              name: 8080